version: '3.7'
services:
  dind:
    image: docker:dind
    user: root
    privileged: true
    container_name: dind
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    user: root
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST:"tcp://docker:2376"
      - DOCKER_CERT_PATH:"/certs/client"
      - DOCKER_TLS_VERIFY:"1"
    networks:
      - jenkins

networks:
  jenkins:
    external: false

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:
